### ISSUE TITLE
Instagram reels do not convert

### ISSUE THREAD

**Issue by jwrobertson86** [stekc/Keto-Bot#4]
Hello:

First off, really loving the bot so far. Just from the little bit of testing I've done it does simplify the process a lot.

I have noticed, however, that the one thing it doesn't handle well yet is Instagram reels. It just gives us the video preview as a still image, but no embedded video. Is this subject to ongoing development?

Thank you for your time.

J

**Comment by jwrobertson86** [comment]
Further context: It appears that some reels work and some do not. For example, this reel:

https://www.instagram.com/reel/C9MxF0eqSAD/?igsh=MXc1c2R1bm9vc2RrcA==

worked just fine, while this one:

https://www.instagram.com/p/C-KrjF4xcYv/?e=e5fc220a-2bf9-4a27-85c0-cd22fec85c59&g=5

did not

It's not clear to me if this is a function of the URL type, if it's a specific issue with TikTok reposts to Instagram, or something else.

**Comment by stekc** [comment]
Instagram is blocking ddinsta, I’ll add QuickVids support and use dd as a fallback when I have time but it might take a few days.

**Comment by bhumit070** [comment]
Hey @stekc I think the issue seems like this 
if I use this link 
- https://www.instagram.com/reel/C_2FW1_y7h7/

It works but if the same link contains reels in the URL like below 


- https://www.instagram.com/reels/C_2FW1_y7h7/

It says invalid link, it should work as both are the same link

<img width="536" alt="Screenshot 2024-09-18 at 18 57 04" src="https://github.com/user-attachments/assets/eb6f529e-4867-464f-bb2c-b4b14a58d102">

Please have a look

**Comment by stekc** [comment]
> Hey @stekc I think the issue seems like this if I use this link
> 
> * https://www.instagram.com/reel/C_2FW1_y7h7/
> 
> It works but if the same link contains reels in the URL like below
> 
> * https://www.instagram.com/reels/C_2FW1_y7h7/
> 
> It says invalid link, it should work as both are the same link
> 
> <img alt="Screenshot 2024-09-18 at 18 57 04" width="536" src="https://private-user-images.githubusercontent.com/63059063/368587599-eb6f529e-4867-464f-bb2c-b4b14a58d102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjMsIm5iZiI6MTcyNjY3MjUyMywicGF0aCI6Ii82MzA1OTA2My8zNjg1ODc1OTktZWI2ZjUyOWUtNDg2Ny00NjRmLWJiMmMtYjRiMTRhNThkMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE1MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTJjZGU2NDMzNDY4MDY0NzY2ODU2MTEzZWYzNDVhNGQ4MmZiM2VkZjRlMGZkY2VkNjQwZjM5N2U4ZmYwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHEq9qbZryJOhxriT8MEGpPeXPpH2oQSFjMhK8XMh8k">
> Please have a look

This is a different issue but I updated the regex and it'll work with /reels/ now. Thanks for letting me know.
