### ISSUE TITLE
Delete messages that has ?igsh in url

### ISSUE THREAD

**Issue by bhumit070** [stekc/Keto-Bot#5]
Hello @stekc  we gotta work on this because when reels link shared with igsh the account can be doxed,

and we need to fix it, 

the proposal is if we find any ?igsh link in the original message we
- reply to the original message
- delete the original message

That will help us keeping our insta account safe

**Comment by stekc** [comment]
Fixed in 1f79621. The bot will delete the original message, add a warning to it's reply and quote whatever the user said. I'm also going to try to add this feature for TikTok links but that's a little trickier since the URLs are identical.

**Comment by bhumit070** [comment]
@stekc this works perfectly, 
but the issue is can we send something like 

sent by <DISPLAY NAME> 
link


???
formatted in such a way because currently it just delets the message and we don't know who sent it?
